# Generated by Django 5.0.1 on 2024-02-13 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
                ('customer_mobile', models.BigIntegerField()),
                ('customer_balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_mobile', models.BigIntegerField()),
                ('supplier_address', models.TextField()),
                ('supplier_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('admin', 'admin'), ('member', 'member')], max_length=100)),
                ('user_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brand_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=200)),
                ('category_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='website.category_model')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_model', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('product_quantity', models.IntegerField()),
                ('product_unit', models.CharField(max_length=200)),
                ('product_base_price', models.FloatField()),
                ('product_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=200)),
                ('product_date', models.DateField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.brand_model')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category_model')),
                ('product_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.supplier_model')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_shipped', models.IntegerField()),
                ('order_date', models.DateField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customer_model')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product_model')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('purchase_date', models.DateField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product_model')),
                ('Supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.supplier_model')),
            ],
        ),
    ]
